name: Run Console Project

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: false
        default: 'develop'

jobs:
  run-console:
    runs-on: self-hosted

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v3

      - name: Clone Private Repository
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git clone --branch ${{ github.event.inputs.branch || 'develop' }} https://x-access-token:${PAT_TOKEN}@github.com/educup/educup-server.git

      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
        env:
          DOTNET_INSTALL_DIR: $HOME/dotnet

      - name: Add .NET to PATH
        run: |
          echo 'export PATH=$PATH:$HOME/dotnet' >> ~/.bashrc
          source ~/.bashrc

      - name: Check .NET SDK Version
        run: dotnet --version

      - name: Restore .NET packages
        run: dotnet restore educup-server/Playground/VAConsole/VAConsole.csproj --locked-mode

      - name: Build the project
        run: dotnet build educup-server/Playground/VAConsole/VAConsole.csproj --configuration Release

      - name: Run the console project
        run: dotnet run --project educup-server/Playground/VAConsole/VAConsole.csproj --configuration Release
